---
stages:
  - test

yamllint:
  stage: test
  tags:
    - core
  image: pipelinecomponents/yamllint:amd64-6f941ff
  rules:
    - changes:
        - ".yamllint"
        - ".gitattributes"
        - "**/*.yaml"
        - "**/*.yml"
  script:
    - yamllint -f colored .

ha-config-check:
  stage: test
  tags:
    - core
  image: ghcr.io/home-assistant/home-assistant:2026.3.0
  rules:
    - changes:
        - "configuration.yaml"
        - "automations.yaml"
        - "scripts.yaml"
        - "scenes.yaml"
        - "**/*.yaml"
        - "**/*.yml"
  script:
    - hass --script check_config --config .
