pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:rgnissen202/ha-config.git
          - cd ha-config.git
          - git push --mirror https://github.com/LordPsycho202/ha-config.git