sensor:
  - name: CPU Temp
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unique_id: cpu_temp
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(1) }}"