---
title: Red Alert
theme: LCARS Red Alert
type: custom:grid-layout
icon: mdi:hazard-lights
path: security
subview: true
back_path: downstairs
badges: []
layout:
  grid-template-columns: 40% 60%
  grid-template-rows: auto
  grid-template-areas: |
    "header headerR"
    "menu main"
    "footer footer"
  mediaquery:
    '(max-width: 600px)':
      grid-template-columns: 95%
      grid-template-areas: |
          "header"
          "main"
          "headerR"
          "aux"
cards:
  - !include ../includes/header.yaml
  - !include ../includes/headerR.yaml

  - type: vertical-stack
    view_layout:
      grid-area: menu
      show:
        mediaquery: '(min-width: 600px)'
    cards:
      - type: markdown
        content: '# Locks'
        card_mod:
          class: header-right
          style: |
            ha-card > * {
              font-family: Antonio
            }

      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: none
        icon: mdi:garage
        name: "Lock: Shuttle Bay Door"
        entity: binary_sensor.garage_door
        show_state: true
        card_mod:
          class: button-bullet-right
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: binary_sensor.aarlo_motion_driveway
        name: "Prox: Shuttle Bay Door"
        icon: mdi:garage
        show_state: true
        card_mod:
          class: button-bullet-right
          style: |
            ha-card > * {
              font-family: Antonio
            }

      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: lock.front_door
        name: "Lock: Forward Airlock"
        icon: mdi:door
        show_state: true
        card_mod:
          class: button-bullet-right
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: binary_sensor.doorbell_motion_detected
        name: "Prox: Forward Airlock"
        icon: mdi:door
        show_state: true
        card_mod:
          class: button-bullet-right
          style: |
            ha-card > * {
              font-family: Antonio
            }

      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: lock.back_door
        name: "Lock: Aft Airlock"
        icon: mdi:door
        show_state: true
        card_mod:
          class: button-bullet-right
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: binary_sensor.aarlo_motion_back_door
        name: "Prox: Aft Airlock"
        icon: mdi:door
        show_state: true
        card_mod:
          class: button-bullet-right
          style: |
            ha-card > * {
              font-family: Antonio
            }

  - type: vertical-stack
    view_layout:
      grid-area: main
    cards:
      - type: markdown
        content: "# Downstairs"
        card_mod:
          class: header-left
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - type: custom:aarlo-glance
        card_mod:
          class:middle-left
        entities:
          - entity: camera.aarlo_driveway
            image_view: arlo-stream
            image_top: previous,name,next
            image_bottom: motion,sound,signal,battery|library,snapshot
          - entity: camera.aarlo_back_door
            image_view: arlo-stream
            image_top: previous,name,next
            image_bottom: motion,sound,signal,battery|library,snapshot
          - camera_view: auto
            type: picture-glance
            title: Doorbell
            entities:
              - entity: binary_sensor.doorbell_motion_detected
              - entity: binary_sensor.doorbell_package_delivered
              - entity: binary_sensor.doorbell_ringing
            image_entity: image.doorbell_event_image
            aspect_ratio: "16:9"
      - type: markdown
        content: "# Hold to activate"
        card_mod:
          class: bar
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - type: horizontal-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: none
            entity: script.bedroom_flic_long_click
            name: All Lights
            show_state: false
            hold_action:
              action: call-service
              service: script.turn_on
              target:
                entity_id: script.bedroom_flic_long_click
              data: {}
            icon: mdi:light-flood-down
            card_mod:
              class: button-bullet-left
              style: |
                ha-card > * {
                  font-family: Antonio
                }
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: none
            entity: switch.aarlo_all_sirens
            hold_action:
              action: toggle
            card_mod:
              class: button-bullet-right
              style: |
                ha-card > * {
                  font-family: Antonio
                }
      - show_name: true
        show_icon: false
        show_state: true
        type: glance
        entities:
          - entity: input_select.mail_status
          - entity: input_boolean.guest_mode
          - entity: input_boolean.vacation_mode
          - entity: sensor.nws_alerts
        columns: 4
        card_mod:
          class: middle-left
          style: |
            ha-card > * {
              font-family: Antonio
            }

  - type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: 40% 60%
      grid-template-rows: auto
      grid-template-areas: |
        "left right"
    view_layout:
      grid-area: footer
      show:
        mediaquery: '(min-width: 600px)'
    cards:
      - type: markdown
        view_layout:
          grid-area: left
        content: "# {{ as_timestamp(now()) | timestamp_custom( '%H:%M' ) }}"
        card_mod:
          class: footer-right
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - type: markdown
        view_layout:
          grid-area: right
        content: "# R: {{states('person.rodney_nissen')}} | J: {{states('person.jfoldennissen')}}"
        card_mod:
          class: footer-left
          style: |
            ha-card > * {
              font-family: Antonio
            }
