---
button_card_templates: !include_dir_merge_named ./includes/templates
decluttering_templates: !include /config/ui-includes/decluttering.yaml

views:
  # Main Views
  - !include views/10-home.yaml
  - !include views/20-weather.yaml
  - !include views/30-rack.yaml
  - !include views/40-garden.yaml
  - !include views/50-planeTracker.yaml
  # Psuedo-Popups
  - !include views/15-security.yaml
  - !include views/16-batteries.yaml
  - !include views/25-wxalert.yaml
