---
title: Red Alert
path: security
icon: mdi:hazard-lights
theme: LCARS Red Alert
subview: true
back_path: /ui-kiosk/home
layout:
  grid-template-columns: 22% 58% 20%
  grid-template-rows: minmax(10%,auto) minmax(auto,60%) 10%
  grid-template-areas: |
    "headerL headerR headerR"
    "menu main aux"
    "sidebar main aux"
    "footer footer footer"
type: custom:grid-layout
badges: []
cards:
  - !include ../includes/headerL.yaml
  - !include ../includes/headerR.yaml
  - !include ../includes/menu.yaml
  - !include ../includes/footer.yaml

  - type: vertical-stack
    view_layout:
      grid-area: aux
    cards:
      - type: custom:html-card
        content: "<font size='5'>Deck A</font>"
        card_mod:
          class: header-open
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - !include /config/ui-includes/space_maps/downstairsMap.yaml
      - type: custom:html-card
        content: '<font size="5">Deck B</font>'
        card_mod:
          class: bar
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - !include /config/ui-includes/space_maps/upstairsMap.yaml

  - type: vertical-stack
    view_layout:
      grid-area: sidebar
    cards:

      - type: custom:html-card
        content: "<font size='5'>Locks</font>"
        card_mod:
          class: middle-right
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: none
        entity: cover.garage_door
        icon: mdi:garage
        name: "Lock: Shuttle Bay Door"
        show_state: true
        card_mod:
          class: button-bullet-left
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: binary_sensor.driveway_motion_detected
        name: "Motion Sensor: Shuttle Bay Door"
        icon: mdi:garage
        show_state: true
        card_mod:
          class: button-bullet-left
          style: |
            ha-card > * {
              font-family: Antonio
            }

      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: lock.front_door
        name: "Lock: Forward Airlock"
        icon: mdi:door
        show_state: true
        card_mod:
          class: button-bullet-left
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: binary_sensor.doorbell_motion_detected
        name: "Motion Sensor: Forward Airlock"
        icon: mdi:door
        show_state: true
        card_mod:
          class: button-bullet-left
          style: |
            ha-card > * {
              font-family: Antonio
            }

      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: lock.back_door
        name: "Lock: Aft Airlock"
        icon: mdi:door
        show_state: true
        card_mod:
          class: button-bullet-left
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: binary_sensor.back_porch_motion_detected
        name: "Motion Sensor: Aft Airlock"
        icon: mdi:door
        show_state: true
        card_mod:
          class: button-bullet-left
          style: |
            ha-card > * {
              font-family: Antonio
            }

  - type: vertical-stack
    view_layout:
      grid-area: main
    cards:
      - type: custom:html-card
        content: "<font size='5'>Viewscreen</font>"
        card_mod:
          class: header-left
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - camera_view: auto
                type: picture-glance
                title: Doorbell
                entities:
                  - entity: binary_sensor.doorbell_motion_detected
                  - entity: binary_sensor.doorbell_package_delivered
                  - entity: binary_sensor.doorbell_ringing
                image_entity: image.doorbell_event_image
                aspect_ratio: "16:9"
              - camera_view: auto
                type: picture-glance
                title: Driveway
                entities:
                  - entity: binary_sensor.driveway_motion_detected
                  - entity: binary_sensor.driveway_person_detected
                image_entity: image.driveway_event_image
                aspect_ratio: "16:9"
          - type: horizontal-stack
            cards:
              - camera_view: auto
                type: picture-glance
                title: Backyard
                entities:
                  - entity: binary_sensor.backyard_motion_detected
                  - entity: binary_sensor.backyard_person_detected
                image_entity: image.backyard_event_image
                aspect_ratio: "16:9"
              - camera_view: auto
                type: picture-glance
                title: Back Porch
                entities:
                  - entity: binary_sensor.back_porch_motion_detected
                  - entity: binary_sensor.back_porch_person_detected
                image_entity: image.back_porch_event_image
                aspect_ratio: "16:9"
          - type: custom:html-card
            content: "<font size='5'>Information</font>"
            card_mod:
              class: bar
              style: |
                ha-card > * {
                  font-family: Antonio
                }
          - show_name: true
            show_icon: false
            show_state: true
            type: glance
            entities:
              - entity: input_select.mail_status
              - entity: input_boolean.guest_mode
              - entity: input_boolean.vacation_mode
              - entity: sensor.nws_alerts
            columns: 4
            card_mod:
              class: middle-blank
              style: |
                ha-card > * {
                  font-family: Antonio
                }

          - type: custom:html-card
            content: "<font size='5'><b>Hold to Activate</b></font>"
            card_mod:
              class: bar
              style: |
                ha-card > * {
                  font-family: Antonio
                }
          - type: horizontal-stack
            cards:
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: none
                entity: script.bedroom_flic_long_click
                name: All Lights
                show_state: false
                hold_action:
                  action: call-service
                  service: script.turn_on
                  target:
                    entity_id: script.bedroom_flic_long_click
                  data: {}
                icon: mdi:light-flood-down
                card_mod:
                  class: button-lozenge-left
                  style: |
                    ha-card > * {
                      font-family: Antonio
                    }
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: none
                entity: switch.chickadee
                hold_action:
                  action: toggle
                card_mod:
                  class: button-lozenge-left
                  style: |
                    ha-card > * {
                      font-family: Antonio
                    }
