---
title: Red Alert
path: security
icon: mdi:hazard-lights
theme: LCARS Red Alert
subview: true
back_path: /ui-kiosk/home
layout:
  grid-template-columns: 22% 58% 20%
  grid-template-rows: minmax(10%,auto) minmax(auto,60%) 10%
  grid-template-areas: |
    "headerL headerR headerR"
    "menu main aux"
    "sidebar main aux"
    "footer footer footer"
type: custom:grid-layout
badges: []
cards:
  - !include ../includes/headerL.yaml
  - !include ../includes/headerR.yaml
  - !include ../includes/menu.yaml
  - !include ../includes/footer.yaml

  - type: vertical-stack
    view_layout:
      grid-area: aux
    cards:
      - type: markdown
        content: "# Deck A"
        card_mod:
          class: header-open
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - !include ../includes/space_maps/downstairsMap.yaml
      - type: markdown
        content: "# Deck B"
        card_mod:
          class: bar
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - !include ../includes/space_maps/upstairsMap.yaml

  - type: vertical-stack
    view_layout:
      grid-area: sidebar
    cards:
 
      - type: markdown
        content: "# Locks"
        card_mod:
          class: middle
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: cover.garage_door_2
        name: "Lock: Shuttle Bay Door"
        show_state: true
        card_mod:
          class: button-bullet
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: binary_sensor.aarlo_motion_driveway
        name: "Motion Sensor: Shuttle Bay Approach"
        icon: mdi:garage
        show_state: true
        card_mod:
          class: button-bullet
          style: |
            ha-card > * {
              font-family: Antonio
            }

      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: lock.front_door
        name: "Lock: Forward Airlock"
        icon: mdi:door
        show_state: true
        card_mod:
          class: button-bullet
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: binary_sensor.aarlo_motion_doorbell
        name: "Motion Sensor: Front Airlock"
        icon: mdi:door
        show_state: true
        card_mod:
          class: button-bullet
          style: |
            ha-card > * {
              font-family: Antonio
            }

      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: lock.back_door
        name: "Lock: Aft Airlock"
        icon: mdi:door
        show_state: true
        card_mod:
          class: button-bullet
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: binary_sensor.aarlo_motion_back_door
        name: "Motion Sensor: Aft Airlock"
        icon: mdi:door
        show_state: true
        card_mod:
          class: button-bullet
          style: |
            ha-card > * {
              font-family: Antonio
            }

  - type: vertical-stack
    view_layout:
      grid-area: main
    cards:
      - type: markdown
        content: "# Viewscreen"
        card_mod:
          class: header-open
          style: |
            ha-card > * {
              font-family: Antonio
            }
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:aarlo-glance
                entity: camera.aarlo_doorbell
                image_view: arlo-stream
                image_top: name|date
                image_bottom: motion,sound,signal|library,snapshot
                image_click: stream
                library_sizes: 3,4,2
              - type: custom:aarlo-glance
                entity: camera.aarlo_back_door
                image_view: arlo-stream
                image_top: name|date
                image_bottom: motion,sound,signal,battery|library,snapshot
                image_click: stream
                library_sizes: 3,4,2
          - type: horizontal-stack
            cards:
              - type: custom:aarlo-glance
                entity: camera.aarlo_driveway
                image_view: arlo-stream
                image_top: name|date
                image_bottom: motion,sound,signal,battery|library,snapshot
                image_click: stream
                library_sizes: 3,4,2
              - type: custom:aarlo-glance
                entity: camera.aarlo_kitty_loft
                image_view: arlo-stream
                image_top: name|date
                image_bottom: motion,sound,signal|library,snapshot
                image_click: stream
                library_sizes: 3,4,2

          - type: markdown
            content: "# Hold to activate"
            card_mod:
              class: bar
              style: |
                ha-card > * {
                  font-family: Antonio
                }
          - type: horizontal-stack
            cards:
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: none
                entity: script.bedroom_flic_long_click
                name: All Lights
                show_state: false
                hold_action:
                  action: call-service
                  service: script.turn_on
                  target:
                    entity_id: script.bedroom_flic_long_click
                  data: {}
                icon: mdi:light-flood-down
                card_mod:
                  class: button-bullet
                  style: |
                    ha-card > * {
                      font-family: Antonio
                    }
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: none
                entity: switch.aarlo_all_sirens
                hold_action:
                  action: toggle
                card_mod:
                  class: button-bullet
                  style: |
                    ha-card > * {
                      font-family: Antonio
                    }
